### ISSUE TITLE
Django image has an error

### ISSUE THREAD

**Issue by YTeyddie22** [bryton90/bryton90#1]
found this svg that i think will help with the image for django. 
[<img align="left" alt="django" width="30px" src="https://www.svgrepo.com/show/353656/django.svg" />]

**Comment by YTeyddie22** [comment]
URL = https://www.svgrepo.com/show/353656/django.svg

img align="left" alt="django" width="30px" src=" URL"

**Comment by YTeyddie22** [comment]
I've have sent a pull request to solve the problem chief 💯

**Comment by bryton90** [comment]
Doesn't seem to work from my end. Where exactly do I place it? I've been
looking at the error for 2hrs now lol
